### ISSUE TITLE
Bug in pmemobj_persist usage?

### ISSUE THREAD

**Issue by poussa** [pmem/pmdk-examples#10]
Isn't this a bug in the example:

https://github.com/pmem/pmdk-examples/blob/c3d079e52cd18b0e14836ef42bad9a995336bf90/hello_world/libpmemobj/hello_libpmemobj.c#L81

Shouldn't it be something like this:

```c
        pmemobj_persist(pop, rootp, sizeof(struct my_root));
```

First, `&rootp->len` works but if you change the order of the members in the struct, it breaks. Second, in only syncs 4 bytes vs entire struct which is 34 bytes.

**Comment by poussa** [comment]
Actually, after re-reading the code, I think the intention is first to sync the len (4 byes) and after that the string itself via `pmemobj_memcpy_persist`. Is this correct reading?

**Comment by eberroca** [comment]
Actually, there is a bug, but not what you point out. First, the program should persist the string, and then it should persist the length. By persisting the length first, it can cause a bug in a reader if the program then crash before writing anything (it is telling that there is a string of length "len" when there really isn't).

This example is very simple and since the size of the struct is really under 64B (i.e., a cache line), the library is most likely flushing all together anyway if they are in the same CL. Although, and since the allocation was not done aligned, that may not be the case.

**Comment by poussa** [comment]
Ah, okay. However, if you sync the string first and then the app crashes. That wold lead to a situation that the string is stored but not the length, correct? You would need a transaction to make it totally correct? But as you said, the sample is simple and transaction is out of scope.

**Comment by eberroca** [comment]
Exactly. However, there is not issue if the string is persisted and not the length. A reader will most likely check If (length > 0) to make sure there is a string there. The length here acts as a "valid flag" for the correctness of the data structure.

**Comment by eberroca** [comment]
If length==0, the reader does not know if the string is reading is real data or garbage.

**Comment by eberroca** [comment]
Fixed
